docRoot                   $VH_ROOT/html/

enableGzip                1

index  {
  useServer               0
  indexFiles              index.php, index.html
}

errorlog $VH_ROOT/logs/$VH_NAME.error.log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}

accesslog $VH_ROOT/logs/$VH_NAME.access.log {
  useServer               0
  rollingSize             10M
  keepDays                7
}

context /.well-known/acme-challenge/ {
  location                $DOC_ROOT/.well-known/acme-challenge/
  allowBrowse             1
}

context / {
  location                $DOC_ROOT/
  allowBrowse             1
  rewrite  {
    RewriteFile .htaccess
  }
}

rewrite {
  enable                  1
  autoLoadHtaccess        1
  logLevel                0
}

vhssl  {
  keyFile                 $SERVER_ROOT/conf/vhosts/$VH_NAME/ssl/ssl.key
  certFile                $SERVER_ROOT/conf/vhosts/$VH_NAME/ssl/ssl.crt
  certChain               1
  sslProtocol             24
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableStapling          0
  ocspRespMaxAge          86400
}
